// src/components/Dialog/index.tsx
import type { FunctionalComponent, JSX } from "preact";
import { useEffect, useRef, useState } from "preact/hooks";
import { forwardRef } from "preact/compat";
import './dialog.css'

const Dialog = forwardRef<HTMLDialogElement>(
  (args: JSX.HTMLAttributes<HTMLDialogElement>, ref) => {
    return (
      <dialog className="dd" {...args} ref={ref}>
        {args.children}
        <form method="dialog">
          <button>✕</button>
        </form>
      </dialog>
    );
  },
);

export default (args: {
  children: (D: {
    openDialog: () => void;
    closeDialog: () => void;
    ref: Ref<HTMLDialogElement>;
    Dialog: FunctionalComponent<{
      ref: Ref<HTMLDialogElement>;
    }>;
  }) => JSX.Element;
}) => {
  const ref_dialog = useRef<HTMLDialogElement>(null);

  const openDialog = () => {
    ref_dialog?.current?.showModal();
  };

  const closeDialog = () => {
    ref_dialog?.current?.close();
  };

  useEffect(() => {
    const dialog = ref_dialog.current;

    if (!dialog) {
      return;
    }

    const handleClick = (ev: MouseEvent) => {
      ev.stopPropagation();

      if (ev.target !== dialog) {
        return;
      }

      const bounds = dialog.getBoundingClientRect();
      const offsetX = ev.clientX - bounds.left;
      const offsetY = ev.clientY - bounds.top;

      if (
        offsetX < 0 || offsetX > bounds.width ||
        offsetY < 0 || offsetY > bounds.height
      ) {
        closeDialog();
      }
    };

    dialog.addEventListener("click", handleClick);

    return () => {
      dialog.removeEventListener("click", handleClick);
    };
  }, []);

  return args.children({
    Dialog,
    openDialog,
    closeDialog,
    ref: ref_dialog,
  });
};

// src/components/wc-dialog.ts
import './wc-dialog.css'

class WCDialog extends HTMLDialogElement {
  constructor() {
    super()

    const showModal = this.showModal.bind(this)
    const show = this.show.bind(this)
    const close = this.close.bind(this)
    const that = this

    this.classList.add("wc-dialog")

    function fadeClose () {
      close()
      that.removeEventListener('transitionend', fadeClose)
    }

    this.showModal = () => {
      this.classList.add('in')
      showModal()
    }

    this.show = () => {
      this.classList.add('in')
      show()
    }

    this.close = () => {
      this.addEventListener('transitionend', fadeClose)
      this.classList.remove('in')
    }

    const onCancel = (ev : Event) => {
      ev.preventDefault()
      ev.stopImmediatePropagation()
      this.close()
    }

    this.addEventListener('cancel', onCancel)
    this.addEventListener('submit', onCancel)

    this.addEventListener(
      'click',
      (ev: MouseEvent | TouchEvent) => {
        const touch = ev as TouchEvent
        const click = ev as MouseEvent
        const b = this.getBoundingClientRect?.()
        let offsetX = 0
        let offsetY = 0

        if (ev.type === 'touchstart') {
          offsetX = touch.touches[0].clientX - b.left
          offsetY = touch.touches[0].clientY - b.top
        } else {
          offsetX = click.clientX - b.left
          offsetY = click.clientY - b.top
        }

        if (
          offsetX < 0 ||
          offsetX > b.width ||
          offsetY < 0 ||
          offsetY > b.height
        ) {
          this.close()
        }
      }
    )
  }
}

if (typeof window != 'undefined')
  customElements.define('wc-dialog', WCDialog, {
    extends: 'dialog',
  })
